version: '3.8'

services:
  poll:
    build: ./poll
    ports:
      - "5000:80"
    networks:
      - back-tier
    depends_on:
      redis:
        condition: service_started
      db:
        condition: service_healthy
    env_file:
      - .env  

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - back-tier

  worker:
    build: ./worker
    networks:
      - back-tier
    depends_on:
      db:
        condition: service_healthy  # ✅ Attend que PostgreSQL soit prêt
      redis:
        condition: service_started
    env_file:
      - .env  
    command: [ "sh", "-c", "sleep 10 && java -jar worker-jar-with-dependencies.jar" ]  # ✅ Attente prolongée pour éviter les erreurs de connexion

  db:
    image: postgres:15-alpine
    networks:
      - back-tier
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql  # ✅ Assure l'exécution du script SQL au démarrage
    env_file:
      - .env  
    healthcheck:  # ✅ Vérifie si PostgreSQL est prêt avant de démarrer les autres services
      test: [ "CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB" ]
      interval: 5s
      timeout: 3s
      retries: 5

  result:
    build: ./result
    ports:
      - "5001:80"
    networks:
      - back-tier
    depends_on:
      db:
        condition: service_healthy  # ✅ Attend que PostgreSQL soit prêt
    env_file:
      - .env  
    command: [ "sh", "-c", "sleep 10 && node server.js" ]  # ✅ Attente prolongée pour éviter les erreurs de connexion

volumes:
  db-data:

networks:
  back-tier:
