services:
  poll:
    build: ./poll
    ports:
      - "5000:80"
    networks:
      - poll-tier
    environment:
      - REDIS_HOST=redis

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - poll-tier
      - back-tier

  worker:
    build: ./worker
    networks:
      - back-tier
    environment:
      - REDIS_HOST=redis
      - DB_HOST=db
      - DB_PORT=5432              
      - DB_USER=postgres
      - DB_PASSWORD=mysecretpassword

  db:
    image: postgres:15-alpine
    networks:
      - back-tier
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=votes
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mysecretpassword

  result:
    build: ./result
    ports:
      - "5001:80"
    networks:
      - result-tier
      - back-tier
    environment:
      - DB_HOST=db
      - DB_USER=postgres
      - DB_PASSWORD=mysecretpassword

volumes:
  db-data:

networks:
  poll-tier:
  result-tier:
  back-tier:
